/* tslint:disable */
export const memory: WebAssembly.Memory;
export function blsGenerator(): number;
export function blsGeneratorAsBytes(a: number, b: number): void;
export function blsGeneratorFromBytes(a: number, b: number): number;
export function blsSignKey(a: number, b: number): number;
export function blsSignKeyAsBytes(a: number, b: number): void;
export function blsSignKeyFromBytes(a: number, b: number): number;
export function blsSign(a: number, b: number, c: number): number;
export function blsVerKey(a: number, b: number): number;
export function blsVerKeyAsBytes(a: number, b: number): void;
export function blsVerKeyFromBytes(a: number, b: number): number;
export function blsProofOfPossession(a: number, b: number): number;
export function blsProofOfPossessionAsBytes(a: number, b: number): void;
export function blsProofOfPossessionFromBytes(a: number, b: number): number;
export function blsMultiSignature(a: number, b: number): number;
export function blsMultiSignatureAsBytes(a: number, b: number): void;
export function blsMultiSignatureFromBytes(a: number, b: number): number;
export function blsVerify(a: number, b: number, c: number, d: number, e: number): number;
export function blsVerifyProofOfPossession(a: number, b: number, c: number): number;
export function blsVerifyMultiSig(a: number, b: number, c: number, d: number, e: number, f: number): number;
export function blsSignatureAsBytes(a: number, b: number): void;
export function blsSignatureFromBytes(a: number, b: number): number;
export function __wbindgen_global_argument_ptr(): number;
export function __wbindgen_malloc(a: number): number;
export function __wbindgen_free(a: number, b: number): void;
